export const STATE_CHANGE_START = 'STATE_CHANGE_START'
export const STATE_CHANGE_SUCCES= 'STATE_CHANGE_SUCCES'
export const STATE_CHANGE_FAILURE= 'STATE_CHANGE_FAILURE'

export const INFO_POST_START = 'INFO_POST_START'
export const INFO_POST_SUCCES= 'INFO_POST_SUCCES'
export const INFO_POST_FAILURE= 'INFO_POST_FAILURE'
